server:
  servlet:
    context-path: /api
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    password: postgres
    username: postgres

encryption:
  salt:
    rounds: 10

jwt:
  algorithm:
    key: MySecretKeyThatIsNotStoredInSourceControl
  issuer: user-service
  expiration: 604800

microservices:
  cart:
    url: http://localhost:8083/api
